### ISSUE TITLE
Billboard submission issue

### ISSUE THREAD

**Issue by jungokasai** [YEdenZ/CTC-Billboard#1]
We see the following error from this billboard submission. It looks that there's a problem with your pickled file. Could you check this and if it works fine? 

```
Successfully downloaded ctc_score_models/D-cnndm/doc_to_summ.ckpt
Traceback (most recent call last):
  File "main.py", line 55, in <module>
    scoring(args.src, args.hypo, args.refs, args.outfile)
  File "main.py", line 43, in scoring
    scores.append(scorer.score(doc=src_s, refs=[], hypo=hyp_s, aspect='consistency'))
  File "/opt/conda/lib/python3.7/site-packages/ctc_score/summarization_scorer.py", line 16, in score
    return self.score_consistency(**kwargs)
  File "/opt/conda/lib/python3.7/site-packages/ctc_score/summarization_scorer.py", line 23, in score_consistency
    aligner = self._get_aligner('doc_to_summ')
  File "/opt/conda/lib/python3.7/site-packages/ctc_score/scorer.py", line 51, in _get_aligner
    aligner.load_state_dict(torch.load(ckpt_path))
  File "/opt/conda/lib/python3.7/site-packages/torch/serialization.py", line 585, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/opt/conda/lib/python3.7/site-packages/torch/serialization.py", line 755, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.
```

**Comment by jungokasai** [comment]
Looks like this is also related to a problem in your original code that someone else caught: https://github.com/tanyuqian/ctc-gen-eval/issues/5.

Thank you!

**Comment by YEdenZ** [comment]
We have resolved the issue, please update the ctc version by  `pip install ctc-score --upgrade` and rerun the code. Thanks!

**Comment by jungokasai** [comment]
Thank you so much for the update. I was able to run this code. I will share results very soon!
